from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    AddCommentView,
    AlertListView,
    ArchivedProjectListView,
    DismissAlertView,
    EmailLoginView,
    MyTasksView,
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
    ProjectUpdateView,
    TaskAssignView,
    TaskCreateView,
    TaskDeleteView,
    TaskDetailView,
    TaskListView,
    TaskStatusChangeView,
    TaskUnassignView,
    TaskUpdateView,
    add_member,
    archive_project,
    remove_member,
    restore_project,
)

urlpatterns = [
    path("login/", EmailLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("projects/", ProjectListView.as_view(), name="project_list"),
    # Fixed paths before parameterised ones to avoid ambiguity.
    path("projects/new/", ProjectCreateView.as_view(), name="project_create"),
    path("projects/archived/", ArchivedProjectListView.as_view(), name="project_archived_list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("projects/<int:pk>/edit/", ProjectUpdateView.as_view(), name="project_edit"),
    path("projects/<int:pk>/archive/", archive_project, name="project_archive"),
    path("projects/<int:pk>/restore/", restore_project, name="project_restore"),
    path("projects/<int:project_pk>/tasks/new/", TaskCreateView.as_view(), name="task_create"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("tasks/<int:pk>/edit/", TaskUpdateView.as_view(), name="task_edit"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("tasks/<int:pk>/status/", TaskStatusChangeView.as_view(), name="task_status_change"),
    path("tasks/<int:pk>/assign/", TaskAssignView.as_view(), name="task_assign"),
    path("tasks/<int:pk>/unassign/", TaskUnassignView.as_view(), name="task_unassign"),
    path("projects/<int:pk>/members/add/", add_member, name="project_add_member"),
    path("projects/<int:pk>/members/<int:user_id>/remove/", remove_member, name="project_remove_member"),
    path("tasks/", TaskListView.as_view(), name="task_list"),
    path("tasks/mine/", MyTasksView.as_view(), name="my_tasks"),
    path("tasks/<int:pk>/comments/add/", AddCommentView.as_view(), name="task_comment_add"),
    path("alerts/", AlertListView.as_view(), name="alert_list"),
    path("tasks/<int:pk>/alerts/dismiss/", DismissAlertView.as_view(), name="alert_dismiss"),
]
